// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lflrqcxqscqqyhojqynv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmbHJxY3hxc2NxcXlob2pxeW52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3OTM1ODQsImV4cCI6MjA2ODM2OTU4NH0.n-3mZuQWgGiLh9L-39F7V_vh3HkflAifBlI3VvarvWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});